.TH bitmap2component 1 "January 19, 2017" "bitmap2component"

.SH NAME
bitmap2component \- converts a bitmap graphic into a footprint or component.

.SH DESCRIPTION
.PP
.B bitmap2component
The bitmap2component can create a footprint or a component from black/white
bitmap graphic or a logo. It's possible to create a output file for eeschema
(*.lib), pcbnew (*.kicad_mod), postscript (*.ps) or the pl_editor
(*.kicad-wks).

.SH SYNOPSIS
.B bitmap2component

.SH AUTHOR
Carsten Schoenert <c.schoenert@t-online.de>
