.TH dxf2idf 1 "January 19, 2017" "dxf2idf"

.SH NAME
dxf2idf \- creates an IDF component outline file from a dxf file.

.SH DESCRIPTION
.PP
.B dxf2idf
This program takes line, arc, and circle segments from a DXF file and creates
an IDF component outline file. dxf2idf is part of the KiCad suite.

.SH SYNOPSIS
.B dxf2idf

.SH AUTHOR
Carsten Schoenert <c.schoenert@t-online.de>
