.TH idfcyl 1 "January 19, 2017" "idfcyl"

.SH NAME
idfcyl \- generates an outline for a cylindrical component.

.SH DESCRIPTION
.PP
.B idfcyl
This program generates an outline for a cylindrical component. The cylinder
may be horizontal or vertical. A horizontal cylinder may have wires at one or
both ends. A vertical cylinder may have at most one wire which may be placed
on the left or right side. idfcyl is part of the KiCad suite.

.SH SYNOPSIS
.B idfcyl

.SH AUTHOR
Carsten Schoenert <c.schoenert@t-online.de>
