.TH idfrect 1 "January 19, 2017" "idfrect"

.SH NAME
idfrect \- generates an outline for a rectangular component.

.SH DESCRIPTION
.PP
.B idfrect
This program generates an outline for a rectangular component. The component
may have a single lead (axial) or a chamfer on the upper left corner. idfrect
is part of the KiCad suite.

.SH SYNOPSIS
.B idfrect

.SH AUTHOR
Carsten Schoenert <c.schoenert@t-online.de>
