.TH pcb_caculator 1 "January 19, 2017" "pcb_caculator"

.SH NAME
pcb_caculator \- tools for calculating the environment on a PCB.

.SH DESCRIPTION
.PP
.B pcb_caculator
A tool for planing and calculating the width of traces, voltage regulators, for
electrical spacings and RF Attenuators. Also information about color codes for
resistors and information about board classes are shown.

.SH SYNOPSIS
.B pcb_caculator

.SH AUTHOR
Carsten Schoenert <c.schoenert@t-online.de>
