#!/usr/bin/python3

'''
Really simple test to see if the pcbnew package can be imported.
Right now there are no additional functional tests. If you can provide some
usefull tests here please provide your suggestions via the BTS.

'''

import pcbnew
